import { Pacifico, Rowdies } from "next/font/google";
import "./globals.css";

export const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export const rowdies = Rowdies({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rowdies",
  preload: true,
});

export const metadata = {
  title: {
    default: "Welcome to Ay Pizza",
    template: "%s : Ay Pizza",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full ">
      <body
        className={`${rowdies.variable} ${pacifico.variable}  antialiased h-full`}
      >
        {children}
      </body>
    </html>
  );
}
