import BtnScrollToTop from "@/app/_components/BtnScrollToTop";
import Footer from "@/app/_components/Footer";
import Navigation from "@/app/_components/Navigation";
import ScrollToTopOnRoute from "@/app/_components/ScrollToTopOnRoute";
import { getCartItems } from "@/app/_libs/cartActions";

import { Toaster } from "react-hot-toast";
import { auth } from "../_libs/auth";
import { getUserProfile } from "../_libs/checkoutActions";

export const metadata = {
  title: {
    default: "Welcome to Ay Pizza",
    template: "%s : Ay Pizza",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUserProfile();

  const cartItems = (await getCartItems()) || [];

  return (
    <div className="min-h-screen flex flex-col bg-cream-200 text-brown 2xl:max-w-screen-2xl 2xl:mx-auto">
      <Navigation user={user} cartItems={cartItems} />
      <main className="grow bg-cream-200 font">{children}</main>
      <Footer />
      <ScrollToTopOnRoute />
      <BtnScrollToTop />
      <Toaster
        position="top-center"
        reverseOrder={false}
        gutter={8}
        containerStyle={{ margin: "20px" }}
        toastOptions={{
          style: {
            background: "#fff3e0",
            color: "#5c3d2e",
            fontSize: "16px",
            maxWidth: "500px",
            padding: "10px 20px",
          },
          success: {
            duration: 3000,
            iconTheme: {
              primary: "#4caf50",
              secondary: "#ffffff",
            },
          },
          error: {
            duration: 5000,
            iconTheme: {
              primary: "#f44336",
              secondary: "#ffffff",
            },
          },
        }}
      />
    </div>
  );
}
