import BtnScrollToTop from "@/app/_components/BtnScrollToTop";

import ScrollToTopOnRoute from "@/app/_components/ScrollToTopOnRoute";
import { Pacifico, Rowdies } from "next/font/google";
import "../globals.css";

import AdminHeader from "./AdminHeader";
import { Toaster } from "react-hot-toast";
import { getUserProfile } from "../_libs/checkoutActions";

export const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export const rowdies = Rowdies({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rowdies",
});

export const metadata = {
  title: {
    default: "Welcome to Ay Pizza",
    template: "%s : Ay Pizza",
  },
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getUserProfile();

  return (
    <div className="flex flex-col bg-cream-200 text-brown 2xl:max-w-screen-2xl 2xl:mx-auto min-h-screen">
      <AdminHeader user={user} />
      <main className="grow bg-cream-200">{children}</main>
      <ScrollToTopOnRoute />
      <BtnScrollToTop />
      <Toaster
        position="top-center"
        reverseOrder={false}
        gutter={8}
        containerStyle={{ margin: "20px" }}
        toastOptions={{
          style: {
            background: "#fff3e0",
            color: "#5c3d2e",
            fontSize: "16px",
            maxWidth: "500px",
            padding: "10px 20px",
          },
          success: {
            duration: 3000,
            iconTheme: {
              primary: "#4caf50",
              secondary: "#ffffff",
            },
          },
          error: {
            duration: 5000,
            iconTheme: {
              primary: "#f44336",
              secondary: "#ffffff",
            },
          },
        }}
      />
    </div>
  );
}
