import BtnScrollToTop from "@/app/_components/BtnScrollToTop";

import ScrollToTopOnRoute from "@/app/_components/ScrollToTopOnRoute";
import { Pacifico, Rowdies } from "next/font/google";
import "../globals.css";

import AdminHeader from "./AdminHeader";

export const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

export const rowdies = Rowdies({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rowdies",
});

export const metadata = {
  title: {
    default: "Welcome to Ay Pizza",
    template: "%s : Ay Pizza",
  },
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <div className="flex flex-col bg-cream-200 text-brown 2xl:max-w-screen-2xl 2xl:mx-auto min-h-screen">
      <AdminHeader />
      <main className="grow bg-cream-200">{children}</main>
      <ScrollToTopOnRoute />
      <BtnScrollToTop />
    </div>
  );
}
